### ISSUE TITLE
Nombres de variables

### ISSUE THREAD

**Issue by DanBaDo** [naxinga/generador-dominios#1]
En esta práctica resulta complicado encontrar nombres de variables que resulten claros, pero es muy importante para que el código se pueda entender en el futuro. ¿A día de hoy, entiendes qué hace la siguiente linea?

https://github.com/naxinga/generador-dominios/blob/a50e15b9b74fc287260bda594754289dafebcb4f/src/app.js#L32

**Comment by naxinga** [comment]
console.log(pronombre+adjetivo+nombre+domi);

así lo he dejado que queda bastante mas claro.
